spring.application.name=resenias

# Base de datos MySQL / Laragon
spring.datasource.url=jdbc:mysql://localhost:3306/db_resenias?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto (usa 8086 para no chocar con los otros ms)
server.port=8086

# URLs de otros microservicios
# ms-usuario  → 8080
# ms-restaurante → 8081
# ms-productos → 8082
# ms-pedidos  → 8083
# ms-carrito  → 8084
# ms-resenias → 8086
ms.pedidos.url=http://localhost:8083
