server:
  port: 8090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ruta-usuarios
              uri: lb://USUARIO
              predicates:
                - Path=/api/v1/usuarios/**
            - id: ruta-repartidores
              uri: lb://REPARTIDORES
              predicates:
                - Path=/api/v1/repartidores/**
            - id: ruta-pagos
              uri: lb://PAGOS
              predicates:
                - Path=/api/v1/pagos/**
            - id: ruta-productos
              uri: lb://MS-PRODUCTOS
              predicates:
                - Path=/api/productos/**
            - id: ruta-notificaciones
              uri: lb://NOTIFICACIONES
              predicates:
                - Path=/api/notificaciones/**
            - id: ruta-resenias
              uri: lb://RESENIAS
              predicates:
                - Path=/api/resenias/**
            - id: ruta-pedidos
              uri: lb://PEDIDOS
              predicates:
                - Path=/api/pedidos/**
            - id: ruta-carrito
              uri: lb://CARRITO
              predicates:
                - Path=/api/carrito/**
            - id: ruta-categorias
              uri: lb://categorias
              predicates:
                - Path=/api/categorias/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
